lawrencegripper/azbrowse

- help.go
- itemview.go
- main.go
This PR allows the user to switch between the list and the JSON views using left/right keys. It also preserves the CTRL-E toggle, but that could easily be removed if this was felt to be redundant.
In addition to updating the Help with appropriate text, I've taken the liberty of using slightly different unicode arrows, which I felt were slightly easier to read. Happy to be told otherwise.
> Allow use of Left/Right keys to switch between list and JSON 

- .travis.yml
- help.go
- main.go
- statusbar.go
- treeview.go
This was a super weird one. 
1. I had two "ctrl+H" registered (copy and paste error). 
2. "keyBackspace" and "keyCtrlH" did the same thing (I've removed keybackspace and now just use keybackspace2)
While I was messing around right and left arrows now go back and forward in the navigation stack too
> Fix #27 Help toggling also triggering back

- treeview.go
Fix uncaptured loop variable that caused the last defined handler to always be used
Extend handler timeout to 10 mins when `debug` flag is specified
> Updates to handler refactoring

- handlers/action.go
- handlers/resourcegroup.go
- handlers/subscription.go
- handlers/types.go
- treeview.go
Closes #37 
This also optimizes the handler allowing `IsPrimaryResponse` to be set on a result to indicate that this is the content to be shown to the user, this minimizes duplicate calls to resources for some handlers. 
If no primary response is set the generic handler calls the resources id.
> Fix actions in the new handler model

- .vscode/launch.json
- endpoints/endpointinfo.go
- endpoints/endpointinfo_test.go
- handlers/appservice.go
- handlers/types.go
- treeview.go
AppServiceExpander is currently a partial implementation of AppService specific functionality. The goal is to use this to explore further integration that can be driven from the ARM API Swagger definitions.
Bonus addition in this PR is the addition of `launch.json` config to set up interactive debugging of azbrowse running in a separate terminal.
> Add partial implementation of AppServiceExpander

- endpoints/endpointinfo.go
- handlers/appservice.go
Expands the type of sub-items handled by AppServiceExpander in preparation for deriving this behaviour from Swagger
> Handle sub-resources (slots, siteextensions)

- cmd/azbrowse/help.go
- internal/pkg/handlers/utils.go
Fixes https://github.com/lawrencegripper/azbrowse/issues/55 by replacing the current "white sun" glyph...
https://unicode-table.com/en/1F323/
... with the "white sun with rays" glyph...
https://unicode-table.com/en/263C/
... as the former appears to be unsupported on MacOS
> Make the Sun Shine on MacOS and Fix #55

- README.md
- internal/pkg/config/config.go
- internal/pkg/keybindings/bindings.go
Migrate `.azbrowse-bindings.json` to `.azbrowse-settings.json`
This change opens up reuse of a single file to hold other settings for azbrowse. The original content of `.azbrowse-bindings.json` because a `keyBindings` property in the new `.azbrowse-settings.json` file.
So 
```json
{
"Help": "F12"
}
```
becomes
```json
{
"keyBindings": {
"Help": "F12"
}
}
```
> Change keybindings file to more generic config file

- .vscode/launch.json
- README.md
- internal/pkg/config/config.go
- internal/pkg/keybindings/listhandlers.go
This PR makes the editor used for the ListUpdate action configurable.
The editor command and arguments can be configured in addition to controlling whether the temp file path should be converted from Linux to Windows paths under WSL. By default VS Code is still used as the editor and whether or not to translate the path is dynamically determined.
Note: currently this only supports graphical editors. Terminal-based editors still need more work - see #96
> Make the ListUpdate editor configurable

- .vscode/launch.json
- internal/pkg/handlers/register.go
- internal/pkg/handlers/storageManagementPolicies.go
The storage API currently doesn't provide a way to list management policies for a storage account
I.e. no `GET` `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Storage/storageAccounts/{accountName}/managementPolicies`
This means that there is no way to navigate via swagger from the account to the management policies
Any policy that exists also currently has to have the name "default" (i.e. can only actually have 0 or 1)
This PR adds an expander that adds the link from storage account to management policy to enable viewing/updating the policy
> Add expander to allow access to Storage Management Policies

- .github/workflows/stale.yml
This will flag then close stale issues and PRs. 
Setting `no-stale` on an issue or `awaiting-approval` on a PR should prevent them being closed if currently blocked.
> Flag then close stale issues or PRs

- internal/pkg/eventing/eventing.go
- internal/pkg/views/statusbar.go
The Pubsub bus used channels with a capacity of 1 so publish operations blocked if the receiver wasn't keeping up. 
In this PR I've:
- increased the capacity to 30
- made publish non-blocking if capacity is exhausted
- optimized the `statusWidget` so it batch processes as this was the main culprit
> Fix perf issue due to blocking and slowing everything down

- internal/pkg/handlers/metrics.go
- internal/pkg/handlers/swagger.go
- internal/pkg/views/treeview.go
Add node IDs in Swagger handler to fix `A crash occurred: ids must be unique or the navigate command breaks` error
> Fix issues from navigate command changes

- .devcontainer/Dockerfile
Just adding the Azure CLI installation to the Dev Dockerfile to address #131 
We could add config to devcontainer.json to mount .azure but this doesn't currently work in WSL2 because if you launch VSCode in WSL2 it actually opens in Windows using the WSL Remote Dev extension, this stops you then being able to open the directory using the SSH Remote Dev extension. So you have to launch code directly in Windows with the source code on your Windows FS and setup Docker for Desktop Tech Preview to spin up a docker container in WSL. This works ok but means the mount path would have to be relative to your Windows Filesystem i.e. `\\wsl$\Ubuntu\home\jjcollinge`. I'm not sure how configurable the `devcontainer.json` file is so I haven't added this.
> Added az cli install

- .devcontainer/Dockerfile
Added a change of ownership for the GOPATH in the Dev container Dockerfile.
Without this I was getting permission issues when building.
issue: #130
> Add change of ownership for GOPATH for Dev Container

- internal/pkg/handlers/containerRegistry.go
The change to add the `navigate` command added validation that node IDs are populated.
This PR ensures that nodes for container registries, tags, etc have valid IDs
> Fix container registry treenode IDs

- cmd/azbrowse/main.go
After debugging, it turns out that the IDs returned from ARM aren't 100% consistent in casing, so this PR makes the path matching case-insensitive
> Fix erratic `navigate` failures

- cmd/swagger-codegen/main.go
- internal/pkg/handlers/swagger-armspecs.generated.go
- pkg/swagger/swagger.go
- pkg/swagger/swagger_test.go
- pkg/swagger/types.go
Add ability to rewrite the generated endpoints
Use endpoint rewriting to patch up VMSS endpoints that didn't align in casing and path segment naming
> Patch up VMSS swagger with overrides

- cmd/azbrowse/main.go
- internal/pkg/expanders/search-swaggerApiSet.go
- internal/pkg/keybindings/defaults.go
- internal/pkg/keybindings/keyhandlers.go
- internal/pkg/keybindings/listhandlers.go
- internal/pkg/views/commandpanel.go
Add new command to allow search queries to be invoked under the `docs` node
See https://docs.microsoft.com/en-us/rest/api/searchservice/search-documents#bkmk_examples for example queries.
> Add Azure Search query invocation

- internal/pkg/storage/store.go
Only show the "do you have another instance of Azbrowse open" message after we've actually been waiting to open it
> Only show 'waiting' message after waiting

- internal/pkg/views/list.go
Fixes #171 
Have tested this change with a code-change to add a sleep in the expander and confirm that a status message is output and that you can retry
> Remove panic on timeout/error expanding list

- cmd/azbrowse/main.go
- internal/pkg/errorhandling/recovery.go
- internal/pkg/expanders/expander.go
- internal/pkg/expanders/resourcegroup.go
- internal/pkg/tracing/appdash.go
- internal/pkg/views/notifications.go
- internal/pkg/views/statusbar.go
- pkg/armclient/armclient.go
This change will catch a `panic` and ensure `azbrowse` returns the terminal to a working state before it closes.
> Cleanup terminal on crash

- cmd/azbrowse/cmd.go
Added some improvements to the output of `--help/-h`.
```
Usage:  azbrowse [OPTIONS] COMMAND
A terminal browser for Microsoft Azure.
Options:
-debug
run in debug mode
-demo
run in demo mode to filter sensitive output
-fuzzer int
run fuzzer (optionally specify the duration in minutes) (default -1)
-navigate string
navigate to resource
Global Options:
-h, --help
print help information
Commands:
version       print version information
```
Addresses: #184
> Improve help output

- Makefile
- cmd/swagger-codegen/main.go
- internal/pkg/expanders/swagger-armspecs.generated.go
- pkg/swagger/swagger.go
Perform url sorting at a folder level rather than file level when generating the hierarchy so that hierarchies across files are reliably structured.
Looking at the diff on the generated code this seems to improve the hierarchy for a bunch of resource types. Storage was what I was looking at when I discovered this and you can now drill down to a blob container level (including deleting containers)!
> Improve hierarchy in swagger-codegen

- internal/pkg/expanders/swagger-armspecs.generated.go
- pkg/swagger/swagger.go
Fix #202 
This is a draft showing moving to using the full `templatedUrl` for swagger sort.
> Move to full path comparison during sort

- azure-pipelines.yaml
- internal/pkg/views/itemview.go
Fixes devcontainer linter warning about unkeyed composites in a dependency-defined structure. This is unsafe, because the dependency could change field order, possibly while still being syntactically valid, yeilding inconsistent behaviour.
Fixes #193
> bugfix(itemview): Use keyed literals

- .vscode/settings.json
This prevents warning with a popup in vscode when gopls is not running the latest version. We pin our gopls version for consistency, and don't want to have to deal with this popup each time the container is used.
Fixes #209
> Bugfix(gopls): Prevent warning about outdated gopls

- internal/pkg/storage/store.go
Minor simplification of the startup code that outputs the "do you have another instance open" message
> Simplify startup warning message code

- Makefile
- internal/pkg/keybindings/listhandlers.go
- internal/pkg/views/itemview.go
- internal/pkg/views/list.go
Leaf node navigation now stores the node on the Content view and the ListUpdate command now checks the Content view node. This allows resource editing to work without reverting to behaviour that allows infinite expansion of a leaf node.
PR also changes `make debug` to use `dlv debug` as this gives a richer debug experience compared to debugging the compiled binary. Happy to pull this into a separate PR if preferred
Fixes #222
> Re-enable "Update current item" command

- cmd/azbrowse/main.go
- internal/pkg/keybindings/itemhandlers.go
- internal/pkg/keybindings/listhandlers.go
Fixes #234 
Move `ListCopyItemIDHandler` to `ItemCopyItemIDHandler` and take a `ContentWidget` instead of `ListWidget` to get the current item
> Move ListCopyItemIDHandler to ItemCopyItemIDHandler

- Makefile
- cmd/swagger-codegen/main.go
- cmd/swagger-codegen/main_tmpl.go
- custom-swagger-specs/databricks.json
- internal/pkg/expanders/databricks-swaggerApiSet.go
- internal/pkg/expanders/databricks.generated.go
- internal/pkg/expanders/databricks.go
- internal/pkg/expanders/registerExpanders.go
- pkg/armclient/armclient.go
- pkg/armclient/authutils.go
- pkg/swagger/swagger.go
- pkg/swagger/types.go
Supports 
* browsing into clusters, jobs, runs, secret scopes, groups, instance-pools and tokens.
* deletion for some resources (resources that support deletion and have a tree node for the individual resource)
Not yet implemented
* workspace, DBFS
* Update of resources
> Initial Databricks workspace browsing

- cmd/azbrowse/main.go
- internal/pkg/keybindings/keyhandlers.go
- internal/pkg/keybindings/listhandlers.go
- internal/pkg/views/commandpanel.go
- internal/pkg/views/list.go
* Adds a new command to the command palette to sort the items in the list alphabetically by name (case-insensitive sort)
* Doesn't have a default shortcut key, but users can configure a shortcut
* Updates the command palette so that if the filter applied has reduced the list of commands to a single command, it is auto-selected (this allows the following sequence of keys to sort the list `Ctrl+p sort<enter>`
> Add command to sort list items

- .devcontainer/Dockerfile
- Makefile
- README.md
- cmd/azbrowse/cmd.go
- cmd/azbrowse/main.go
- cmd/azbrowse/selfupdate.go
- docs/config.md
- go.mod
- go.sum
- internal/pkg/storage/store.go
- internal/pkg/storage/store_test.go
Fixes #248 
- Add environment vars to disable the check or force it
- Tweak devcontainer to fix locale error seen in bash
- Cache the account list from `az` command to improve autocompletion perf
> Improve startup and autocompletion performance

- .devcontainer/Dockerfile
- cmd/azbrowse/cmd.go
Fixes #273 
When autocompeting subs with spaces in their name things now function correctly.
> Correctly escape spaces in sub names

- cmd/azbrowse/main.go
- internal/pkg/automation/fuzzer.go
- internal/pkg/expanders/expander.go
- internal/pkg/views/list.go
- internal/pkg/views/notifications.go
- internal/pkg/views/statusbar.go
This PR ensures that the `statusbar` messages appear in a timely fashion and the correct messages show with loading indicators during loading.
To do this it:
1. Reworks the logic which decides which message to show
2. Moves code which blocked the gocui drawing go routine into it's own goroutine. Note this means we now have locking implemented in `list.go` to ensure only one navigation takes place at a time.
3. Uses basic change tracking in update loops to ensure we only redraw if we have too (previously would redraw every second regardless)
Added benefit of this work is reduced CPU usage when idle.
> Fix status bar lag, optimise UI redraw

- Makefile
- internal/pkg/views/itemview.go
Should improve performance
closes #292 PageDn failing on single line content
There's still room for improvement as the PageDown handling computes the number of lines based on the count of `\n` characters in the content, and doesn't account for line wrapping
> Format on SetContent

- internal/pkg/views/itemview.go
Reverts the Copy Content command to copying text without the terminal colour sequences
> Retain original content and return in GetContent

- internal/pkg/expanders/containerRegistry.go
- internal/pkg/expanders/cosmos-db.go
- internal/pkg/expanders/expander.go
- internal/pkg/expanders/registerExpanders.go
- internal/pkg/expanders/storageBlob.go
- internal/pkg/expanders/swagger.go
- internal/pkg/expanders/types.go
- internal/pkg/keybindings/listhandlers.go
- internal/pkg/views/list.go
Adds initial data plane support for cosmos
* support for listing documents in a sql database
* support to viewing, updating and deleting a document in a sql database (by selecting via the list)
Additional changes
- when expanding and item and an error is returned with no response content, the error is displayed as the content
- when dealing with paged node lists, new items are added in-place of the "more..." node - closes #282
- Move Update to expander closes #169
> Initial Cosmos DB data plane support

- .github/workflows/build.yaml
- Push updated build of devcontainer on main
This change is aimed at speeding up PR builds by ensuring the devcontainer 
image is pushed and available for the docker cache to use on most builds.
> Push devcontainer on main

- internal/pkg/views/list.go
Fixes #315 
- Prevent multiple concurrent refreshes (since refresh performs a Back and Navigate using the current list state)
- Disable UI updates during a refresh (to mask the Back/Navigate actions)
> Only allow single Refresh at a time

- internal/pkg/eventing/eventing.go
- internal/pkg/views/notifications.go
- internal/pkg/views/statusbar.go
Fixes #307
- The status notifications weren't correctly triggering a UI update when processing expired notifications.
- Pending delete list wasn't cleared until after deleting had finished. It is not cleared as delete is started.
> Fix #307: Confirming delete doesn't update UI

- cmd/swagger-codegen/main.go
- internal/pkg/expanders/swagger-armspecs.generated.go
- Add config to handle static web app POST-as-GET endpoints
- make swagger-codegen
> Add config to handle static web app POST-as-GET endpoints

- internal/pkg/views/itemview.go
- internal/pkg/views/list.go
This makes filtering case insensitive. 
Currently, the items in the list have ToLower applied, but the filter itself doesn't. This results in a filter of `M` not finding anything, my `m` will find items that include both upper and lower case `m` characters.
> Compare Filter using ToLower

- scripts/swagger_update/app.py
Actions are failing to gen swagger as an additional include for blob storage is getting added to a file storage profile and so the file doesn't exist on disk. 
https://github.com/lawrencegripper/azbrowse/runs/4509600496?check_suite_focus=true
> Attempt to fix swagger gen

- scripts/swagger_update/api_set.py
Marketplace catalog readme has a YAML block with missing end closing block. This makes swagger update handle this by skipping the badly formed version.
> Handle missing codeblock finish in readme

- pkg/armclient/authutils.go
Fixes #478 
As per discussion in linked issue, this PR updates the auth to use `NewAzureCLICredential` rather than `NewDefaultAzureCredential`
> Switch to AzureCLICredential

- Gemfile.lock
- scripts/release.rb
I've bumped the version of the `docker-api` gem as per [this issue](https://github.com/upserve/docker-api/issues/586) and that seems to addresses the [CI failure](https://github.com/lawrencegripper/azbrowse/actions/runs/10150688701/job/28068348472?pr=579#step:5:1013)
> Update docker-api gem

- .devcontainer/Dockerfile
- cmd/azbrowse/main.go
- cmd/swagger-codegen/main.go
- internal/pkg/expanders/containerApp.go
- internal/pkg/expanders/registerExpanders.go
- internal/pkg/expanders/swagger-armspecs.generated.go
- internal/pkg/keybindings/keyhandlers.go
- internal/pkg/keybindings/list_containerapp_logs.go
- pkg/swagger/swagger.go
- pkg/swagger/types.go
Add support for viewing container app logs
- support drilling into the containers under a revision's replica
- add command to view logs for a container
- support streaming logs and cancel context to terminate log request when user navigates away from the log view
Also updates the dev container to include `GOPATH/bin` in the `PATH` so that `azbrowse` is found in the release script after running `make install`
> Add support for viewing container app logs

- .devcontainer/Dockerfile
- go.mod
Update from go 1.20 to go 1.24 to support newest dependabot PRs
> chore: go v1.24 update
