lawrencegripper/azbrowse

armclient/authutils.go
=> Force `az account get-access-token` to JSON output

README.md, actions.go, armclient/armclient.go, itemview.go, main.go, treeview.go, version/version.go
Closes #10 
This PR adds checks to the status code response of ARM, currently the `armclient` doesn't check for non-success codes in the response.
=> Added status code checks

actions.go, eventing/eventing.go, handlers/action.go, handlers/generic.go, handlers/subscription.go, statusbar.go, treeview.go
Closes #33 closes #34 closes #36
=> Fix: Status and Title issues

Gopkg.lock, Gopkg.toml, Makefile, cmd/azbrowse/itemview.go, cmd/azbrowse/main.go, cmd/azbrowse/treeview.go, internal/pkg/handlers/deployments.go, internal/pkg/handlers/generic.go, internal/pkg/handlers/resourcegroup.go, internal/pkg/handlers/types.go, internal/pkg/handlers/utils.go, pkg/armclient/types.go, vendor/github.com/TylerBrock/colorjson/LICENSE, vendor/github.com/TylerBrock/colorjson/README.md, vendor/github.com/TylerBrock/colorjson/colorjson.go
=> Support for browsing deployments #24 Bonus: Added color to the json

Makefile, README.md, scripts/install_dev_tools.sh
Mostly an enhancement of the README, with a few clean up jobs in the install script and the Makefile.
=> Enhance set up instructions for people like me

.golangci.toml, Makefile, cmd/swagger-codegen/main.go, internal/pkg/handlers/activitylog.go, internal/pkg/handlers/generic.go, internal/pkg/handlers/json.go, internal/pkg/handlers/register.go, internal/pkg/handlers/resourcegroup.go, internal/pkg/handlers/subscription.go, internal/pkg/handlers/swagger.generated.go, internal/pkg/handlers/swagger.go, internal/pkg/handlers/types.go, internal/pkg/handlers/utils.go, internal/pkg/views/actions.go, internal/pkg/views/itemview.go, internal/pkg/views/treeview.go, pkg/armclient/types.go, scripts/release.sh
#67 
Also fix some navigation bugs
=> Add basic activity log #67

.goreleaser.yml
Attempt to add scoop and brew installers.
=> Add Scoop and Brew Installers

internal/pkg/handlers/activitylog.go, internal/pkg/handlers/resourcegroup.go, internal/pkg/keybindings/listhandlers.go, internal/pkg/views/treeview.go
=> Fix activity log viewer

README.md, cmd/azbrowse/main.go, internal/pkg/keybindings/defaults.go, internal/pkg/keybindings/keyhandlers.go, internal/pkg/keybindings/listhandlers.go, internal/pkg/views/treeview.go
Additional support for navigating lists:
* PageUp
* PageDown
* Home
* End
=> Extend list navigation

README.md, internal/pkg/handlers/activitylog.go
=> Fix event ordering

internal/pkg/views/help.go
Fix #92 
Reported by @ohthehugemanatee
=> Add quit command to help

cmd/azbrowse/main.go
Capture the error and close gocui when subscriptions fail to load
so that the terminal is returned to a usable state
=> Add handling to close gocui when subscriptions fail to load

internal/pkg/keybindings/listhandlers.go, internal/pkg/views/treeview.go
When scrolling up and down long lists the behaviour seemed a little unintuitive. This change hopefully makes the behaviour feel more natural
=> Update list scrolling behaviour

internal/pkg/keybindings/globalhandlers.go
=> Add clipboard error message

Makefile, internal/pkg/keybindings/globalhandlers.go, internal/pkg/keybindings/listhandlers.go, internal/pkg/wsl/utils.go
=> Add WSL utils and handle setting clipboard text

Makefile, cmd/azbrowse/main.go, internal/pkg/handlers/containerInstance.go, internal/pkg/handlers/generic.go, internal/pkg/handlers/register.go, internal/pkg/keybindings/defaults.go, internal/pkg/keybindings/itemhandlers.go, internal/pkg/keybindings/keyhandlers.go, internal/pkg/views/itemview.go, internal/pkg/views/notifications_test.go, pkg/armclient/types.go
=> Support viewing container instance logs

cmd/azbrowse/main.go, internal/pkg/keybindings/defaults.go, internal/pkg/keybindings/keyhandlers.go, internal/pkg/keybindings/listhandlers.go, internal/pkg/views/list.go
A few ideas for filtering:
* Highlight the filter matches
* Use the Back action to clear the filter if set. Once cleared, normal Back action takes effect
* Use Display text for filtering rather than name as Display is what the user sees
* Trigger redraw so that the applied filter matches what user has typed
* Add the filter text to the list title (persists after command palette is dismissed)
* Add a command to clear the filter (defaults to Esc which feels natural to me)
=> Ideas for filter

.goreleaser.yml
Fix for warnings spotted in build output
=> Update go-releaser as per deprecation notices

scripts/update-swagger.sh
PR to test a theory - and hopefully unblock #136
=> Remove Microsoft.Web workaround - fixes #137

pkg/endpoints/endpointinfo.go, pkg/endpoints/endpointinfo_test.go
=> Fix string indexing panic

internal/pkg/expanders/metrics.go
Fixes a crash when using metrics bug causing a crash during navigation.
=> Fix metrics expander bug

CONTRIBUTING.md
Plenty still to do, but wanted to add a starting point :-)
=> Starting point for contrib docs

internal/pkg/expanders/default.go, internal/pkg/expanders/expander.go, internal/pkg/expanders/registerExpanders.go, pkg/armclient/armclient.go
=> Ensure DefaultExpander is initialised before use

cmd/azbrowse/main.go, internal/pkg/keybindings/bindings.go, internal/pkg/keybindings/globalhandlers.go, internal/pkg/keybindings/keyhandlers.go, internal/pkg/keybindings/listhandlers.go, internal/pkg/keybindings/utils.go
Fixes #21 
* Enables commands without a keybinding
* Adds command to copy current item ID
=> Add Copy item ID command

cmd/azbrowse/main.go, internal/pkg/expanders/action.go, internal/pkg/expanders/activitylog.go, internal/pkg/expanders/appInsights.go, internal/pkg/expanders/containerInstance.go, internal/pkg/expanders/containerRegistry.go, internal/pkg/expanders/containerService.go, internal/pkg/expanders/default.go, internal/pkg/expanders/deployments.go, internal/pkg/expanders/json.go, internal/pkg/expanders/metrics.go, internal/pkg/expanders/resourcegroup.go, internal/pkg/expanders/search.go, internal/pkg/expanders/storageManagementPolicies.go, internal/pkg/expanders/subscription.go, internal/pkg/expanders/swagger.go, internal/pkg/expanders/tentant.go, internal/pkg/expanders/types.go, internal/pkg/keybindings/bindings.go, internal/pkg/keybindings/globalhandlers.go, internal/pkg/keybindings/keyhandlers.go, internal/pkg/keybindings/listhandlers.go, internal/pkg/keybindings/utils.go, internal/pkg/storage/store.go, internal/pkg/views/list.go, internal/pkg/views/notifications.go
Merging the latest changes (and handling the conflict with #165
=> Merge latest changes

internal/pkg/keybindings/globalhandlers.go, internal/pkg/keybindings/listhandlers.go
Fix JSON formatting #161
Not sure this is the best way to fix, just had a quick go at getting something working. Any suggestions.
Using `style/colors.go` seemed to add a bunch of color characters so I just used the vanilla json package. Could extract this common funciton to `style/format.go` or something.
FYI: This will conflict with #165
=> Fix JSON formatting #161

cmd/azbrowse/main.go, internal/pkg/errorhandling/recovery.go, internal/pkg/expanders/expander.go, internal/pkg/expanders/resourcegroup.go, internal/pkg/tracing/appdash.go, internal/pkg/views/notifications.go, internal/pkg/views/statusbar.go, pkg/armclient/armclient.go
=> Fixed typo in RecoveryWithCleanUp()

README.md
Fixes #186 - Fixing a small typo in the Readme. 😺😇
=> Fix a small bug in the Readme 🐛📝

cmd/azbrowse/main.go, go.mod, go.sum, internal/pkg/storage/store.go
Fixes #185 
Move from `init` func to explicit `load` func for DB
=> Load DB when needed not with `init` func

cmd/azbrowse/cmd.go, cmd/azbrowse/main.go, docs/command-line.md, internal/pkg/config/config.go, pkg/armclient/armclient.go, pkg/armclient/authutils.go
Add argument to specify which tenant to load subscriptions for and add/update docs
=> Add argument to specify tenant

internal/pkg/views/itemview.go
=> Remove duplicate if condition

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, CONTRIBUTING.md, Makefile, cmd/azbrowse/main.go, internal/pkg/eventing/eventing.go, internal/pkg/eventing/eventing_test.go, internal/pkg/eventing/test_helpers.go, internal/pkg/expanders/action.go, internal/pkg/expanders/containerInstance.go, internal/pkg/expanders/default.go, internal/pkg/expanders/expander.go, internal/pkg/expanders/resourcegroup.go, internal/pkg/keybindings/listhandlers.go, internal/pkg/style/colors.go, internal/pkg/views/actions.go, internal/pkg/views/itemview.go, internal/pkg/views/notifications.go, internal/pkg/views/notifications_arm_async.go, internal/pkg/views/statusbar.go, pkg/armclient/armclient.go
#15 
Bonus, fix some buggy code in the `eventing` package and update some docs. 
Todo:
=> Support Toast notifications for async actions like `Delete` or `Restart`

internal/pkg/eventing/eventing.go, internal/pkg/views/list.go, internal/pkg/views/notifications_arm_async.go
=> Fix panic on async delete

cmd/swagger-codegen/main.go, custom-swagger-specs/databricks.json, internal/pkg/expanders/databricks-swaggerApiSet.go, internal/pkg/expanders/databricks.generated.go, internal/pkg/expanders/databricks.go, internal/pkg/expanders/swagger.go, internal/pkg/keybindings/listhandlers.go, internal/pkg/views/list.go
* Add browsing of Workspace file system (including file contents)
* Add browsing of DBFS (including file contents, if file is under 8k)
* Support editing clusters, jobs, DBFS files and workspace notebooks
* Support deleting files/directories in DBFS and files in Workspace
=> Update databricks integration

.devcontainer/devcontainer.json
Set `name` in `devcontainer.json` to improve window title etc in VSCode
=> Change devcontainer name

internal/pkg/expanders/databricks-swaggerApiSet.go
Fix error when attempting to load run details when browsing runs under jobs
=> Fix up job->run details loading

internal/pkg/views/list.go, internal/pkg/views/stack.go
=> Preserve filter on Back/Refresh

cmd/azbrowse/main.go, internal/pkg/views/list.go, internal/pkg/views/stack.go
* reworked handling current page state in list
* fixed bug: refresh doesn't work if a filter is applied
* sorting and filters now preserved on refresh
=> Preserve sorting and filters on refresh

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .gitignore, internal/pkg/automation/fuzzer.go, internal/pkg/automation/navigateTo.go, internal/pkg/views/list.go
=> Chore: Upgrade to go1.14

cmd/azbrowse/cmd.go, go.mod, go.sum, internal/pkg/filesystem/filesystem_test.go, internal/pkg/filesystem/integration_test.go, internal/pkg/storage/store.go, internal/pkg/storage/store_test.go
=> Moving to diskkv to support multiple instances

Makefile, cmd/azbrowse/cmd.go, cmd/azbrowse/main.go, internal/pkg/storage/store.go, pkg/armclient/armclient.go
=> Move to azgraph rest api 

.devcontainer/Dockerfile, .goreleaser.yml, scripts/ci_release.sh
Works around the build errors seen in #263 due too https://github.com/goreleaser/goreleaser/issues/1715
=> Reenable snap v2

cmd/azbrowse/main.go, internal/pkg/views/itemview.go, internal/pkg/views/list.go, internal/pkg/views/notifications.go, internal/pkg/views/statusbar.go, internal/pkg/views/utils.go, internal/pkg/views/utils_test.go
=> Dynamically size views 

.gitignore, internal/pkg/views/actions.go, internal/pkg/views/list.go
=> Fix missing content in view when going back

README.md
=> Fix build badge to point to github action build

internal/pkg/automation/navigateTo.go
=> Fix navigate to subresources #260

cmd/azbrowse/cmd.go, docs/commandline/azbrowse.md, internal/pkg/automation/navigateTo.go
Closes #252 allowing `azbrowse --resume` or `-r` to start where you left off in the last session.
=> Add option to resume from last session

go.mod, go.sum, internal/pkg/expanders/registerExpanders.go, internal/pkg/expanders/storageBlob.go, internal/pkg/expanders/types.go, internal/pkg/keybindings/listhandlers.go, internal/pkg/views/itemview.go
Browse blobs and metadata
Delete blobs
=> Initial Blob storage implementation

.devcontainer/Dockerfile, .devcontainer/snapbase.Dockerfile, Makefile, scripts/ci_release.sh
Get shiny new stuff from gopls and update the version of go used.
=> Update tooling version for go and devcontainer

internal/pkg/views/notifications.go
=> Correct clear message. Tip for multidelete

internal/pkg/views/notifications.go
Ensure we redraw the UI after someone has accepted a delete.
=> Fix #298 Update UI on delete

cmd/azbrowse/main.go, internal/pkg/expanders/action.go, internal/pkg/expanders/cosmos-db.go, internal/pkg/expanders/expander.go, internal/pkg/expanders/integration_test.go, internal/pkg/expanders/registerExpanders.go, internal/pkg/filesystem/filesystem_test.go, internal/pkg/filesystem/utils.go, internal/pkg/interfaces/views.go, internal/pkg/keybindings/globalhandlers.go, internal/pkg/keybindings/listhandlers.go, internal/pkg/style/colors.go, internal/pkg/views/commandpanel.go, internal/pkg/views/list.go, internal/pkg/views/notifications_test.go
Adds a "Get Document" action to Cosmos DB collection nodes
Changes the status colour from red to yellow for in-progress notifications
=> Add "Get Document" action to Cosmos DB data plane

internal/pkg/expanders/diagnosticSettings.go, internal/pkg/expanders/resourcegroup.go
=> Only display diagsettings when present

.devcontainer/Dockerfile, .goreleaser.yml, internal/pkg/keybindings/bindings.go
Updates to go v1.16 and bumps tools used.
=> chore: update to go v1.16

internal/pkg/views/list.go
Remove keyboard input lag after navigate
=> Fix #311 nav up/down lag

cmd/azbrowse/main.go, internal/pkg/filesystem/filesystem_test.go, internal/pkg/filesystem/utils.go, pkg/armclient/armclient.go
Remove unnecessary `time.sleep` (I'm hunting them down) and fix #313 Provider cache bug.
=> Startup Perf improvements

internal/pkg/keybindings/list_update.go
When a resource group is expanded, the `ResoureGroupExpander` is saved as the expander. Since this doesn't support `Update`, it blocked updating any top-level resources, i.e. those added by the `ResourceGroupExpander`.
When attempting an Update, this PR adds a test to see whether the `SwaggerExpander` can handle it if the item's expander can't. This could be generalised to check all handlers, but the the top-level resources in a resource group the `SwaggerExpander` feels like the most likely candidate .
=> Enable dashboard editing

internal/pkg/expanders/cosmos-db.go
- Propertly set `DeleteURL` for Cosmos DB Document TreeNodes (fixes #327)
- Include partition key with id in TreeNode Display property
=> Fix multi-delete for Cosmos DB documents

cmd/azbrowse/main.go
=> Remove duplicate "Copy current resource ID" command

CONTRIBUTING.md, README.md, docs/design/README.md, internal/pkg/expanders/types.go
This PR looks to explain more about how azbrowse is built for others looking to contribute.﻿
Todo
=> Design Docs v0.1

internal/pkg/editor/editor.go, internal/pkg/expanders/cosmos-db.go, internal/pkg/keybindings/list_update.go
- Extract editor functionality to new pkg
- Add "Add New Document" action for Cosmos DB (creates a template document with `id` and partition key)
=> Add "New Document" action for Cosmos DB

internal/pkg/expanders/subscription.go, internal/pkg/filesystem/filesystem_test.go
=> Enable browsing subscription level deploys

.github/workflows/build.yaml, Makefile
Pre-work for moving to use this: https://github.com/stuartleeks/devcontainer-build-run by @stuartleeks
=> Move to docker buildkit

.github/workflows/armgen.yml
Update the armgen workflow to non-sudo version now the devcontainer isn't running as root.
=> Fix armgen workflow
